name: login_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  firebase_auth: 0.16.1
  cloud_firestore: "^0.13.0"
  provider: ^3.1.0
  razorpay_flutter: ^1.1.1
  fluttertoast: ^3.1.0
  flutter_staggered_grid_view: "^0.3.2"
  carousel_slider: ^1.3.0
  url_launcher: 5.7.2
  firebase_storage: ^3.1.5
  




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  google_fonts: ^1.1.0
  circular_profile_avatar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/0.jpg
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/6.jpg
    - assets/7.jpg
    - assets/deepalayalogo.png
    - images/15.jpg
    - images/16.jpg
    - images/17.jpg
    - images/18.jpg
    - images/19.jpg
    - images/20.jpg
    - images/21.jpg
    - images/22.jpg
    - images/23.jpg
    - images/24.jpg
    - images/25.jpg
    - images/26.jpg
    - images/27.jpg
    - images/28.jpg
    - images/29.jpg
    - images/30.jpg
    - images/31.jpg
    - images/32.jpg
    - images/33.jpg
    - images/34.jpg
    - images/35.jpg
    - images/36.jpg
    - images/h1.jpg
    - images/h2.jpg
    - images/h3.jpg
    - images/h4.jpg
    - images/h5.jpg
    - images/h6.jpg
    - images/h7.jpg
    - images/h8.jpg
    - images/h9.jpg
    - images/p1.jpg
    - images/p2.jpg
    - images/p3.jpg
    - images/p4.jpg
    - images/p5.jpg
    - images/p6.jpg
    - images/p7.jpg
    - images/p8.jpg
    - images/p9.jpg
    - images/p10.jpg
    - images/sponsor.jpg
    - images/sponsor1.jpg
    - images/vid1.png
    - support_images/support1.jpg
    - support_images/support2.jpg
    - support_images/support3.jpg
    - support_images/support4.jpg
    - support_images/support5.jpg
    - support_images/support6.jpg
    - getinvolved_images/getinvolved1.png
    - getinvolved_images/getinvolved2.png
    - getinvolved_images/getinvolved3.png
    - getinvolved_images/getinvolved4.png
    - getinvolved_images/getinvolved5.png
    - getinvolved_images/getinvolved6.png
    - getinvolved_images/getinvolved7.png
    - getinvolved_images/getinvolved8.png
    - getinvolved_images/getinvolved9.png

   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
